[OptimaliseRing]
Taal=nl-NL
;Taal=en-GB
Legenda=True
MapTips=True
Database=.\Databases\Database OptimaliseRing 2011_04_07.mdb
Werkmap=.\\Werkmap
BatchMap=.\Batch
InstellingenMap=.\Instellingen
AchtergrondShapes=.\AchtergrondShapes
Notepad=Notepad.Exe
EMAILinfo=jarl.kind@deltares.nl
ShapeFileDijkringDelen=.\Dijkringdelen\dijkringdelen.shp
ShapeFileDijkringen=.\Dijkringdelen\dww_dijkring2002_1.shp
LineWidth=4
Viewport=-106191.83|388677.80|628484.49|335490.25
LegendaType=0

[Parameters]
JaartalFiguur=2180

;Aimms Parameters
Lowest_segment_fixed=True
Lowest_segment1=0
Lowest_segment2=0

;Aimms Discretizatie
Z=300
Option_convert_solution=True
DiscretizationMethod=Percentage
Nr_variables_1traject=30
Nr_variables_ntraject=100

;Aimms Settings
one_increase_during_period=True
max_Costs=False
minimum_increase=False
two_segments=False
all_at_the_same_time=False
group_at_the_same_time=True
max_increase=250.0
min_increase=5.0
years_until_steady=60.0
years_between_increases=20.0
years_without_increase=40.0
years_until_force_equal=5.0
presolve=True
add_cuts=False
use_incumbents=False
bigM=False
max_iterations_AOA=1000.0
mip_tolerance=1e-13
relative_tolerance=1.0
max_time=60
max_updates=2

;Aimms Partitions
partition_p1=start
partition_start_moment_p1=0
partition_end_moment_p1=60
partition_no_periods_p1=0
partition_pct_p1=40.0

partition_p2=finish
partition_start_moment_p2=60
partition_end_moment_p2=300
partition_no_periods_p2=0
partition_pct_p2=60.0

;Aimms Solve
Case_prefix=Optimalisering
SolutionAlgorithm=Iterateprob
Tune_nr=1
Tune_perc_width=0.50
Tune_tolerance_factor=0.25

[Instellingen]
ZichtJaar=2020
OptimaleOverstromingskansenJaar=2050
DiscontovoetSchade=5.5
DiscontovoetInvesteringen=5.5
EconomischScenario=3
BedragPerInwoner=0
BedragPerDodelijkSlachtoffer=6700
BedragPerGetroffene=12
Aversiefactor=1
BeleidsfactorOverstromingsschade=1.6
AanpassingsfactorOverstromingsschade=1
ParametersKostenfunctie=1
ScenarioVoorHoeveelheidSchade=2
FactorKans=1
FactorKosten=1.11
FactorGroeiSchade=1
RamingVoorSlachtoffers=2
SchadeFunctie=2
TypeKostenfunctie=1
KlimaatScenarioEnFysischMaxAfvoer=17
Veiligheidsnorm=1
DijkringspecifiekeFactorSchade=1
Parametersonzekerheid=0
AantalParameterscenarios=0

[Formulieren]
LegendaFormTop=0
LegendaFormLeft=0

[LegendaItems.0]
Legenda:nl-NL=conform de KKBA
Legenda:en-GB=according to KKBA
LegendaItem1=800|255|51|153|102
LegendaItem2=1600|255|0|255|0
LegendaItem3=2800|255|255|255|0
LegendaItem4=6300|255|255|204|0
LegendaItem5=14000|255|255|0|0
LegendaItem6=28000|255|255|0|255
LegendaItem7=57000|255|204|153|255
LegendaItem8=113000|255|51|102|255
LegendaItem9=0|255|0|255|255

[LegendaItems.1]
Legenda:nl-NL=conform beleidsopties
Legenda:en-GB=according to policy options
LegendaItem1=250|255|255|0|0
LegendaItem2=500|255|255|174|0
LegendaItem3=1000|255|208|255|0
LegendaItem4=2500|255|33|255|92
LegendaItem5=5000|255|18|208|255
LegendaItem6=10000|255|33|74|255
LegendaItem7=25000|255|255|190|232
LegendaItem8=50000|255|255|0|197
LegendaItem9=0|255|76|0|115

[LegendaItems.2]
Legenda:nl-NL=conform normopties
Legenda:en-GB=according to norm options
LegendaItem1=2000|255|255|255|0
LegendaItem2=4000|255|163|255|155
LegendaItem3=10000|255|38|115|0
LegendaItem4=20000|255|255|190|190
LegendaItem5=40000|255|255|0|0
LegendaItem6=0|255|115|0|0

[FillStyles:nl-NL]
FillStyle1=Volledig
FillStyle2=Transparant
FillStyle3=Horizontaal
FillStyle4=Vertikaal
FillStyle5=Diagonaal omhoog
FillStyle6=Diagonaal naar beneden
FillStyle7=Gekruist
FillStyle8=Diagonaal gekruist
FillStyle9=Lichtgrijs
FillStyle10=Grijs
FillStyle11=Donkergrijs

[FillStyles:en-GB]
FillStyle1=Completely
FillStyle2=Transparent
FillStyle3=Horizontal
FillStyle4=Vertical
FillStyle5=Diagonal up
FillStyle6=Diagonal down
FillStyle7=Crossed
FillStyle8=Diagonally crossed
FillStyle9=Light grey
FillStyle10=Grey
FillStyle11=Dark grey

[MarkerStyles:nl-NL]
MarkerStyle1=Cirkel
MarkerStyle2=Vierkant
MarkerStyle3=Driehoek
MarkerStyle4=Kruisje

[MarkerStyles:en-GB]
MarkerStyle1=Circle
MarkerStyle2=Square
MarkerStyle3=Triangle
MarkerStyle4=Cross

[BerekeningenSelecties:nl-NL]
BerekeningenSelectie1=Alles
BerekeningenSelectie2=Bovenrivieren|38:1|38:2|40:1|40:2|41:1|41:2|42:1|43:1|43-1:1|43-2:1|44:1|45:1|47:1|48:1|49:1|50:1|51:1|52:1|53:1
BerekeningenSelectie3=Benedenrivieren zoet|15:1|16:1|22:1|23:1|24:1|24:2|35:1
BerekeningenSelectie4=Benedenrivieren zout|14:2|14:3|17:1|18:1|19:1|20:1|20:2|21:1|25:1|25:2
BerekeningenSelectie5=RBSO|36:1|38:1|38:2|41:1|41:2|42:1|43:1|44:1|45:1|47:1|48:1|49:1|50:1|51:1|52:1|53:1
BerekeningenSelectie6=Maas|36:1|38:2|40:2|41:2|36-1:1|36-2:1
BerekeningenSelectie7=Rijn|38:1|40:1|41:1|42:1|43:1|43-1:1|43-2:1|44:1|45:1|47:1|48:1|49:1|50:1|51:1|52:1|53:1
BerekeningenSelectie8=IJsseldelta|10:1|11:1
BerekeningenSelectie9=WV21 Noord|1:1|2:1|3:1|4:1|5:1|6:1|6:2|6:3|6:4|7:1|8:1|8:2|12:1|13:1|13:2|13:4|44:2|45:2|46:1
BerekeningenSelectie10=WV21 Rivieren|10:1|11:1|15:1|16:1|21:1|22:1|24:1|34:1|35:1|36:1|38:1|38:2|41:1|41:2|42:1|43:1|44:1|45:1|47:1|48:1|48:2|49:1|50:1|51:1|52:1|53:1
BerekeningenSelectie11=WV21 Zuid West|14:1|14:2|14:3|14:4|17:1|18:1|19:1|20:1|20:2|20:3|25:1|25:2|26:1|26:2|27:1|28:1|29:1|29:2|30:1|31:1|32:1|32:2
BerekeningenSelectie12=WV21 KKBA Alles|1:1|2:1|3:1|4:1|5:1|6:1|6:2|6:3|6:4|7:1|8:1|8:2|10:1|11:1|12:1|13:1|13:2|13:4|14:1|14:2|14:3|14:4|15:1|16:1|17:1|18:1|19:1|20:1|20:2|20:3|21:1|22:1|24:1|25:1|25:2|26:1|26:2|27:1|28:1|29:1|29:2|30:1|31:1|32:1|32:2|34:1|35:1|36:1|38:1|38:2|41:1|41:2|42:1|43:1|44:1|44:2|45:1|45:2|46:1|47:1|48:1|48:2|49:1|50:1|51:1|52:1|53:1
BerekeningenSelectie13=WV21 KBA Alles|1:1|2:1|3:1|4:1|5:1|6:1|6:2|6:3|6:4|7:1|8:1|8:2|9:1|10:1|11:1|12:1|13:1|13:2|13:4|13-b:1|14:1|14:2|14:3|15:1|16:1|17:1|18:1|19:1|20:1|20:2|20:3|21:1|22:1|24:1|25:1|25:2|26:1|26:2|27:1|28:1|29:1|29:2|30:1|31:1|32:1|32:2|34:1|34-a:1|35:1|36:1|36-a:1|37:1|38:1|38:2|39:1|40:1|40:2|41:1|41:2|42:1|43:1|44:1|44:2|45:1|45:2|46:1|47:1|48:1|48:2|49:1|50:1|51:1|52:1|53:1|65:1|68:1|86:1|87:1
BerekeningenSelectie14=-
BerekeningenSelectie15=Niets

[BerekeningenSelecties:en-GB]
BerekeningenSelectie1=All
BerekeningenSelectie2=Upper-river area|38:1|38:2|40:1|40:2|41:1|41:2|42:1|43:1|43-1:1|43-2:1|44:1|45:1|47:1|48:1|49:1|50:1|51:1|52:1|53:1
BerekeningenSelectie3=Lower-river area fresh water|15:1|16:1|22:1|23:1|24:1|24:2|35:1
BerekeningenSelectie4=Lower-river area salt water|14:2|14:3|17:1|18:1|19:1|20:1|20:2|21:1|25:1|25:2
BerekeningenSelectie5=RBSO|36:1|38:1|38:2|41:1|41:2|42:1|43:1|44:1|45:1|47:1|48:1|49:1|50:1|51:1|52:1|53:1
BerekeningenSelectie6=Meuse|36:1|38:2|40:2|41:2|36-1:1|36-2:1
BerekeningenSelectie7=Rhine|38:1|40:1|41:1|42:1|43:1|43-1:1|43-2:1|44:1|45:1|47:1|48:1|49:1|50:1|51:1|52:1|53:1
BerekeningenSelectie8=IJsseldelta|10:1|11:1
BerekeningenSelectie9=WV21 North|1:1|2:1|3:1|4:1|5:1|6:1|6:2|6:3|6:4|7:1|8:1|8:2|12:1|13:1|13:2|13:4|44:2|45:2|46:1
BerekeningenSelectie10=WV21 Rivers|10:1|11:1|15:1|16:1|21:1|22:1|24:1|34:1|35:1|36:1|38:1|38:2|41:1|41:2|42:1|43:1|44:1|45:1|47:1|48:1|48:2|49:1|50:1|51:1|52:1|53:1
BerekeningenSelectie11=WV21 South West|14:1|14:2|14:3|14:4|17:1|18:1|19:1|20:1|20:2|20:3|25:1|25:2|26:1|26:2|27:1|28:1|29:1|29:2|30:1|31:1|32:1|32:2
BerekeningenSelectie12=WV21 All INCBA|1:1|2:1|3:1|4:1|5:1|6:1|6:2|6:3|6:4|7:1|8:1|8:2|10:1|11:1|12:1|13:1|13:2|13:4|14:1|14:2|14:3|14:4|15:1|16:1|17:1|18:1|19:1|20:1|20:2|20:3|21:1|22:1|24:1|25:1|25:2|26:1|26:2|27:1|28:1|29:1|29:2|30:1|31:1|32:1|32:2|34:1|35:1|36:1|38:1|38:2|41:1|41:2|42:1|43:1|44:1|44:2|45:1|45:2|46:1|47:1|48:1|48:2|49:1|50:1|51:1|52:1|53:1
BerekeningenSelectie13=WV21 All CBA|1:1|2:1|3:1|4:1|5:1|6:1|6:2|6:3|6:4|7:1|8:1|8:2|9:1|10:1|11:1|12:1|13:1|13:2|13:4|13-b:1|14:1|14:2|14:3|15:1|16:1|17:1|18:1|19:1|20:1|20:2|20:3|21:1|22:1|24:1|25:1|25:2|26:1|26:2|27:1|28:1|29:1|29:2|30:1|31:1|32:1|32:2|34:1|34-a:1|35:1|36:1|36-a:1|37:1|38:1|38:2|39:1|40:1|40:2|41:1|41:2|42:1|43:1|44:1|44:2|45:1|45:2|46:1|47:1|48:1|48:2|49:1|50:1|51:1|52:1|53:1|65:1|68:1|86:1|87:1
BerekeningenSelectie14=-
BerekeningenSelectie15=Nothing

[AchtergrondShapes]
AchtergrondShape1=.\\AchtergrondShapes\waterned.shp|True|255|179|227|228|0|1
AchtergrondShape2=.\\AchtergrondShapes\la_ned.shp|True|255|240|232|205|0|1
AchtergrondShape3=.\\AchtergrondShapes\plaatsen.shp|True|255|234|177|141|0|1
AchtergrondShape4=.\\AchtergrondShapes\den bosch.shp|True|255|153|153|153|0|2
AchtergrondShape5=.\\AchtergrondShapes\tiel.shp|True|255|153|153|153|0|2

[SysteemShapes]
SysteemShape1=.\Dijkringdelen\contournl.shp
SysteemShape2=.\Dijkringdelen\dww_dijkring2002_1.shp

[Messages:nl-NL]
message.0001=Voor de selectie %1 zijn geen dijkring delen aanwezig in de database
message.0002=Opgegeven eerste jaar van de optimalisatie moet groter dan of gelijk zijn aan het hoogste beginjaar.\n\nHoogste beginjaar = %1\nEerste jaar van de optimalisatie = %2
message.0003=Berekening geannuleerd
message.0004=Bestand %1 is geen instellingen bestand

[Messages:en-GB]
message.0001=No dike ring parts present in the database for the selection %1
message.0002=Selected first year of optimisation must be greater than or equal to the highest begin year.\n\nHighest begin year = %1\nFirst year of optimisation = %2
message.0003=Calculation cancelled
message.0004=File %1 is not a settings file

[Formulieren]

[Errors:nl-NL]
error.0001=Kolomnummer %1 is onbekend
error.0002=Deze som is gemaakt met een verouderde versie van OptimaliseRing, openen is niet mogelijk.
error.0003=Fout %1 tijdens het lezen van project file %2
error.0004=Fout %1 tijdens het schrijven van project file %2
error.0005=Instellingen %1 niet gevonden
error.0006=Geen instellingen gevonden in de folder %1
error.0010=Er is een probleem bij het rekenen van Aimms, controleer of Aimms is geinstalleerd of dat er voldoende licenties zijn.
error.1000=Database %1 bestaat niet!
error.1001=Gebruikershandleiding %1 bestaat niet!
error.1002=Legenda item mag niet leeg zijn
error.1003=Legenda item moet groter zijn dan %! en kleiner dan %2
error.1004=%1
error.2000=Bestand %1 is geen geldig bestand
error.2001=Bestand %1 is geen OptimaliseRing database
error.2002='%1'\nquery geeft een foutmelding.
error.2003=Kan de applicatie niet starten omdat de database %1 in gebruik is.

[Errors:en-GB]
error.0001=Column number %1 is unknown
error.0002=This calculation is made by an older version of OptimaliseRing, unable to open the calculation.
error.0003=Error %1 during reading project file %2
error.0004=Error %1 during writing project file %2
error.0005=Settings %1 not found
error.0006=No settings found in folder %1
error.0010=Error starting Aimms.
error.1000=Database %1 does not exist!
error.1001=User manual %1 does not exist!
error.1002=Legend item should not be empty
error.1003=Legend item should be grether than %1 and less than %2
error.1004=%1
error.2000=File %1 is not a valid file
error.2001=File %1 is not a correct OptimaliseRing database
error.2002='%1'\nquery gives an error
error.2003=Unable to run the application because the database %1 is in use.

[Questions:nl-NL]
question.0001=Bij de volgende dijkringdelen:\n\n%1\nis de groei van de investeringen groter dan de discontovoet.\nWilt u voor de overige dijkringdelen rekenen?
question.0002=Wilt u berekening %1 overschrijven?
question.0003=Bewaar de veranderingen in dit project %1?
question.0004=Wilt u deze serie berekeningen '%1' overschrijven?

[Questions:en-GB]
question.0001=For the following dike ring parts:\n\n%1\n the investment grow is larger than the discount rate.\nDo you wish to continue with the other dike ring parts?
question.0002=Overwrite the calculation %1?
question.0003=Save changes for this project %1?
question.0004=Overwrite this series of calculations %1?

[Compartimenteren]

[B-keringen]
